### ISSUE TITLE
bspwm에서 사용하는 폰트 목록

### ISSUE THREAD

**Issue by aNchor-only** [RangHo/dotfiles#4]
아치리눅스 bspwm 유저입니다. 무슨 폰트가 필요한지 알려주실 수 있으신가요....?

**Comment by RangHo** [comment]
제가 사용하는 Makefile 기반 인스톨러 사용하시면 한 번에 필요한 폰트가 전부 설치됩니다. 개별적으로 필요한 폰트가 궁금하시다면 fontconfig 패키지의 [requirements 파일](https://github.com/RangHo/dotfiles/blob/c23087b16fb17d74fa8e81654de3e41e73979f06/fontconfig/requirements#L6-L17)을 참고해 주세요.
